spring:
  application:
    name: ecommerce
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 1106
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.default_batch_fetch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.batch_versioned_data: true
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always